###########################################################################################################
# Tasks to create user "michael" 
###########################################################################################################

---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create a new regular user with sudo privileges
  user:
    name: "{{ my_user }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ my_user }}"
    state: present
    key: "{{ my_ssh_key }}"

- name: Set ansible key for remote user
  authorized_key:
    user: "{{ my_user }}"
    state: present
    key: "{{ my_ansible_ssh_key }}"

- name: Set standard ssh configuration
  copy:
    src: home/.ssh/config
    dest: /home/{{ my_user }}/.ssh/config
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    mode: 0644

- name: Set global git parameters
  template:
    src:  home/.gitconfig.j2
    dest: /home/{{ my_user }}/.gitconfig
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    mode: 0644

- name: Configure bash prompt
  lineinfile:
    path: /home/{{ my_user }}/.bashrc
    regexp: '^#force_color_prompt='
    line: force_color_prompt=yes
 