###########################################################################################################
# Tasks specific to host shallcrm-frontend-vsi-1
###########################################################################################################

---

# Start cockpit daemon
- name: Start Cockpit daemon
  ansible.builtin.systemd:
    state: started
    name: cockpit

