###########################################################################################################
# Tasks to configure ssmtp
###########################################################################################################

---
- name: Install ssmtp
  apt: 
    update_cache=yes
    name=ssmtp
    state=latest

# Note: The template file has been encrypted with Ansible Vault so the playbook must be invoked with "--vault-id user@prompt"
# Need to find alternative method of encrypting or managing secrets on cloud
- name: Copy standard ssmtp configuration file
  template:
    src:  etc/ssmtp/ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Copy standard reverse aliases file
  template:
    src:  etc/ssmtp/revaliases.j2
    dest: /etc/ssmtp/revaliases
    owner: root
    group: root
    mode: 0644
    backup: yes

