###########################################################################################################
# Variables applicable to entire ubuntu group
###########################################################################################################

---
# On IBM Cloud Schematics need to use Playbook "Advanced Options" to specify optional variable ansible_user
ansible_user: ansible

sys_packages: [ 'mc', 'htop', 'curl', 'git', 'ufw', 'software-properties-common', 'avahi-daemon', 'net-tools', 'nfs-common', 'jq' ] 

ssh_allow_users:  "ibmuser ansible ubuntu root"

my_user: ibmuser
git_global_name: "User Name"
git_global_email: git.user@mail.domain

fail2ban_destemail: notification.user@mail.domain
fail2ban_bantime: 86400
fail2ban_findtime: 600
fail2ban_maxretry: 3
fail2ban_sender: "{{ ansible_hostname }}"

ssmtp_hostname: "{{ ansible_hostname }}"
ssmtp_sender: root.sender@mail.domain
ssmtp_mailhub: mail.mail.domain
