###########################################################################################################
# Variables applicable to entire ubuntu group
###########################################################################################################

---
ansible_user: ansible
# ansible_ssh_private_key_file: ~/.ssh/vsi_ansible_pwless_ssh_key
# ansible_python_interpreter: /usr/bin/python3

sys_packages: [ 'mc', 'htop', 'curl', 'git', 'ufw', 'software-properties-common', 'avahi-daemon', 'net-tools', 'nfs-common', 'jq' ] 

ssh_allow_users:  "ibmuser ansible ubuntu"

my_user: ibmuser
# my_ssh_key: "{{ lookup('file', 'home/.ssh/vsi_ibmuser_pwless_ssh_key.pub') }}"
# my_ansible_ssh_key: "{{ lookup('file', 'home/.ssh/vsi_ansible_pwless_ssh_key.pub') }}"
git_global_name: "User Name"
git_global_email: git.user@mail.domain

fail2ban_destemail: notification.user@mail.domain
fail2ban_bantime: 86400
fail2ban_findtime: 600
fail2ban_maxretry: 3
fail2ban_sender: "{{ ansible_hostname }}"

ssmtp_hostname: "{{ ansible_hostname }}"
ssmtp_sender: root.sender@mail.domain
ssmtp_mailhub: mail.mail.domain
